package com.ptit.poker.analytics.infrastructure;

import static org.assertj.core.api.Assertions.assertThat;import com.ptit.poker.analytics.application.timebucket.TimeBucketAnalyticsService;import com.ptit.poker.auth.domain.*;import com.ptit.poker.auth.infrastructure.persistence.*;import com.ptit.poker.game.application.GameSessionPersistenceService;import com.ptit.poker.game.domain.pot.PotType;import com.ptit.poker.game.domain.state.*;import com.ptit.poker.game.infrastructure.persistence.*;import com.ptit.poker.room.domain.*;import com.ptit.poker.room.infrastructure.persistence.*;import com.ptit.poker.support.TestDatabaseSafetyInitializer;import java.time.*;import java.util.*;import java.util.concurrent.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.*;

@EnabledIfEnvironmentVariable(named="TEST_DB_URL",matches=".+") @EnabledIfEnvironmentVariable(named="TEST_DB_USERNAME",matches=".+") @EnabledIfEnvironmentVariable(named="TEST_DB_PASSWORD",matches=".+")
@ActiveProfiles("test") @ContextConfiguration(initializers=TestDatabaseSafetyInitializer.class) @SpringBootTest
class TimeBucketAnalyticsMySqlIntegrationTests {
 @Autowired UserRepository users;@Autowired RoomRepository rooms;@Autowired GameSessionRepository sessions;@Autowired PokerHandRepository hands;@Autowired HandPlayerRepository players;@Autowired PotRepository pots;@Autowired PotAwardRepository awards;@Autowired GameSessionPersistenceService completion;@Autowired TimeBucketAnalyticsService analytics;@Autowired JdbcTemplate jdbc;
 private final List<Long> userIds=new ArrayList<>(),roomIds=new ArrayList<>(),sessionIds=new ArrayList<>();
 @AfterEach void cleanup(){for(long id:sessionIds)jdbc.update("DELETE FROM game_sessions WHERE id=?",id);for(long id:roomIds)jdbc.update("DELETE FROM rooms WHERE id=?",id);for(long id:userIds)jdbc.update("DELETE FROM users WHERE id=?",id);}
 @Test void flywayV8CreatesBothProjectionTables(){assertThat(jdbc.queryForObject("SELECT version FROM flyway_schema_history WHERE success=TRUE ORDER BY installed_rank DESC LIMIT 1",String.class)).isEqualTo("8");assertThat(table("daily_statistics")).isOne();assertThat(table("weekly_statistics")).isOne();}
 @Test void dailyAndWeeklyMetricsUseFinishedAtActualAwardAndAreIdempotent(){UserEntity user=user();long session=session(user,true);Instant base=Instant.parse("2026-08-28T01:00:00Z");long[] nets={100,-40,0,60};long awardHand=0;for(int i=0;i<nets.length;i++){long hand=hand(session,user,i+1,base.plusSeconds(i*120L),base.plusSeconds(i*120L+60),nets[i]);if(i==0)awardHand=hand;}PotEntity pot=pots.saveAndFlush(new PotEntity(awardHand,0,PotType.MAIN,180,100));awards.saveAndFlush(new PotAwardEntity(pot.getId(),user.getId(),90,0));LocalDate day=LocalDate.of(2026,8,28);analytics.refreshDaily(user.getId(),day);analytics.refreshWeekly(user.getId(),day);analytics.refreshDaily(user.getId(),day);var daily=analytics.daily(user.getId(),day,day).getFirst();assertThat(daily.handsPlayed()).isEqualTo(4);assertThat(daily.handsWon()).isEqualTo(2);assertThat(daily.handsLost()).isOne();assertThat(daily.handsTied()).isOne();assertThat(daily.chipsWon()).isEqualTo(160);assertThat(daily.chipsLost()).isEqualTo(40);assertThat(daily.netChips()).isEqualTo(120);assertThat(daily.largestPotWon()).isEqualTo(90);assertThat(daily.sessionsParticipated()).isOne();assertThat(analytics.weekly(user.getId(),day,day).getFirst().handsPlayed()).isEqualTo(4);}
 @Test void oneSessionAcrossBangkokSundayMidnightRefreshesTwoDaysAndWeeks(){UserEntity user=user();long session=session(user,true);hand(session,user,1,Instant.parse("2026-08-30T16:58:00Z"),Instant.parse("2026-08-30T16:59:59Z"),10);hand(session,user,2,Instant.parse("2026-08-30T17:00:00Z"),Instant.parse("2026-08-30T17:01:00Z"),-5);analytics.refreshCompletedSession(session);assertThat(analytics.daily(user.getId(),LocalDate.of(2026,8,30),LocalDate.of(2026,8,31))).extracting(TimeBucketAnalyticsService.Daily::date).containsExactly(LocalDate.of(2026,8,30),LocalDate.of(2026,8,31));assertThat(analytics.weekly(user.getId(),LocalDate.of(2026,8,24),LocalDate.of(2026,8,31))).extracting(TimeBucketAnalyticsService.Weekly::weekStartDate).containsExactly(LocalDate.of(2026,8,24),LocalDate.of(2026,8,31));assertThat(analytics.daily(user.getId(),LocalDate.of(2026,8,30),LocalDate.of(2026,8,31))).allSatisfy(d->assertThat(d.sessionsParticipated()).isOne());}
 @Test void concurrentSameBucketRefreshesConvergeWithoutDuplicates()throws Exception{UserEntity user=user();long session=session(user,true);LocalDate day=LocalDate.of(2026,8,28);hand(session,user,1,Instant.parse("2026-08-28T01:00:00Z"),Instant.parse("2026-08-28T01:01:00Z"),25);runTogether(()->analytics.refreshDaily(user.getId(),day),()->analytics.refreshDaily(user.getId(),day));runTogether(()->analytics.refreshWeekly(user.getId(),day),()->analytics.refreshWeekly(user.getId(),day));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM daily_statistics WHERE user_id=?",Long.class,user.getId())).isOne();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM weekly_statistics WHERE user_id=?",Long.class,user.getId())).isOne();assertThat(analytics.daily(user.getId(),day,day).getFirst().netChips()).isEqualTo(25);}
 @Test void finishingSessionAutomaticallyRefreshesAffectedBucketsAfterCommit(){UserEntity user=user();long session=session(user,false);Instant at=Instant.parse("2026-08-28T04:00:00Z");hand(session,user,1,at,at.plusSeconds(30),20);completion.finishSession(session);assertThat(analytics.daily(user.getId(),LocalDate.of(2026,8,28),LocalDate.of(2026,8,28))).hasSize(1);assertThat(analytics.weekly(user.getId(),LocalDate.of(2026,8,28),LocalDate.of(2026,8,28))).hasSize(1);}
 private long table(String name){return jdbc.queryForObject("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?",Long.class,name);}private UserEntity user(){String s=UUID.randomUUID().toString().replace("-","").substring(0,10);UserEntity u=users.saveAndFlush(new UserEntity("a8_"+s,"hash","a8_"+s+"@example.test",Role.PLAYER,AccountStatus.ACTIVE,5000));userIds.add(u.getId());return u;}private long session(UserEntity owner,boolean finished){Instant now=Instant.parse("2026-08-28T00:00:00Z");RoomEntity room=rooms.saveAndFlush(new RoomEntity("analytics-"+UUID.randomUUID(),owner.getId(),RoomType.PUBLIC,null,6,50,100,1000,RoomStatus.PLAYING,now));roomIds.add(room.getId());GameSessionEntity s=sessions.saveAndFlush(new GameSessionEntity(room.getId(),finished?GameSessionStatus.FINISHED:GameSessionStatus.ACTIVE,now,finished?now.plusSeconds(1000):null));sessionIds.add(s.getId());return s.getId();}private long hand(long session,UserEntity user,int number,Instant start,Instant end,long net){return hand(session,user.getId(),number,start,end,net);}private long hand(long session,long user,int number,Instant start,Instant end,long net){PokerHandEntity h=hands.saveAndFlush(new PokerHandEntity(session,number,1,1,2,50,100,start,end,GamePhase.FINISHED,"",HandEndReason.ALL_OTHERS_FOLDED));players.saveAndFlush(new HandPlayerEntity(h.getId(),user,1,1000,1000+net,100,PokerPlayerState.ACTIVE,true,false,null));return h.getId();}
 private void runTogether(Runnable a,Runnable b)throws Exception{CountDownLatch ready=new CountDownLatch(2),go=new CountDownLatch(1);ExecutorService pool=Executors.newFixedThreadPool(2);try{List<Future<?>> futures=List.of(pool.submit(()->{ready.countDown();go.await();a.run();return null;}),pool.submit(()->{ready.countDown();go.await();b.run();return null;}));assertThat(ready.await(5,TimeUnit.SECONDS)).isTrue();go.countDown();for(Future<?> future:futures)future.get(15,TimeUnit.SECONDS);}finally{pool.shutdownNow();}}
}
