import { useEffect, useRef, useState } from 'react'
import type { RoomDetail } from '../../rooms/types/room'
import { Avatar } from '../../../shared/ui/Avatar'
import { Button } from '../../../shared/ui/Button'
import { EmptyState } from '../../../shared/ui/EmptyState'
import { formatNumber, formatTimestamp } from '../../../shared/lib/format'
import { useRoomChat } from '../hooks/useRoomChat'

import type { GameStatePayload } from '../types/game'

type Tab='chat'|'info'|'players'
function hasIsoControl(value:string){return Array.from(value).some((character)=>{const code=character.codePointAt(0)||0;return code<=31||code===127})}
export function GameSidePanel({room,connected,live=true,game}:{room:RoomDetail;connected:boolean;live?:boolean;game?:GameStatePayload}){
  const authorized = live && room.room.status !== 'FINISHED' && room.room.status !== 'CLOSED'
  const [tab,setTab]=useState<Tab>('chat');const [content,setContent]=useState('');const [retryId,setRetryId]=useState<string|null>(null);const {messages,pendingId,failed,send,historyPending,historyError}=useRoomChat(room.room.id, authorized);const scrollRef=useRef<HTMLDivElement>(null);const shouldFollow=useRef(true)
  useEffect(()=>{const element=scrollRef.current;if(!shouldFollow.current||!element)return;if(typeof element.scrollTo==='function')element.scrollTo({top:element.scrollHeight});else element.scrollTop=element.scrollHeight},[messages])
  const submit=(event:React.FormEvent)=>{event.preventDefault();const normalized=content.trim();if(!authorized||!normalized||Array.from(normalized).length>500||hasIsoControl(normalized))return;const result=send(normalized,retryId||undefined);setRetryId(result.clientMessageId);if(result.sent)setContent('')}
  return <aside className="game-side-panel"><div className="game-tabs" role="tablist" aria-label="Table details">{(['chat','info','players'] as const).map((value)=><button type="button" key={value} id={`game-tab-${value}`} aria-controls={`game-panel-${value}`} tabIndex={tab===value?0:-1} onKeyDown={(event)=>{const tabs=['chat','info','players'] as const;const index=tabs.indexOf(value);const target=event.key==='ArrowRight'?tabs[(index+1)%3]:event.key==='ArrowLeft'?tabs[(index+2)%3]:event.key==='Home'?tabs[0]:event.key==='End'?tabs[2]:null;if(target){event.preventDefault();setTab(target);document.getElementById(`game-tab-${target}`)?.focus()}}} role="tab" aria-selected={tab===value} onClick={()=>setTab(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div>
    {tab==='chat'&&<div className="chat-panel" id="game-panel-chat" aria-labelledby="game-tab-chat" role="tabpanel"><div className="chat-messages" ref={scrollRef} onScroll={(event)=>{const element=event.currentTarget;shouldFollow.current=element.scrollHeight-element.scrollTop-element.clientHeight<48}}>{!authorized&&!messages.length?<EmptyState variant="inline" motif="suit" title="Session finished · Chat is closed." description="Room messages are no longer active."/>:historyPending&&!messages.length?<p role="status">Loading room messages…</p>:historyError&&!messages.length?<EmptyState variant="inline" motif="suit" title="Messages are temporarily unavailable" description="Live room chat will continue while history reconnects."/>:!messages.length?<EmptyState variant="inline" motif="suit" title="No room messages" description="Messages sent in this room appear here."/>:<ol>{messages.map((message)=><li key={message.messageId}><Avatar displayName={message.sender.displayName} src={message.sender.avatarUrl} size="sm"/><div><span><strong>{message.sender.displayName}</strong><time dateTime={message.createdAt}>{formatTimestamp(message.createdAt)}</time></span><p>{message.content}</p></div></li>)}</ol>}</div>{authorized ? <form className="chat-compose" onSubmit={submit}><label className="sr-only" htmlFor="chatContent">Room message</label><input id="chatContent" value={content} maxLength={500} placeholder={connected?'Message the room':'Reconnecting…'} disabled={!connected||Boolean(pendingId&&!failed)} onChange={(event)=>{setContent(event.target.value);setRetryId(null)}}/><Button type="submit" disabled={!connected||!content.trim()} loading={Boolean(pendingId&&!failed)} loadingLabel="Sending…">{failed?'Retry':'Send'}</Button>{failed&&<p role="alert">Message was not sent. Try again when connected.</p>}</form> : messages.length ? <p className="chat-closed">Session finished · Chat is closed.</p> : null}</div>}
    {tab==='info'&&<dl className="game-info" id="game-panel-info" aria-labelledby="game-tab-info" role="tabpanel"><div><dt>Room</dt><dd>{room.room.name}</dd></div><div><dt>Blinds</dt><dd>{formatNumber(room.room.smallBlind)} / {formatNumber(room.room.bigBlind)}</dd></div><div><dt>Buy-in</dt><dd>{formatNumber(room.room.buyIn)}</dd></div><div><dt>Access</dt><dd>{room.room.roomType}</dd></div><div><dt>Seats</dt><dd>{room.room.seatedPlayers} / {room.room.maxPlayers}</dd></div></dl>}
    {tab==='players'&&<ul className="game-player-list" id="game-panel-players" aria-labelledby="game-tab-players" role="tabpanel">{room.members.map((member)=>{const player=game?.players.find((candidate)=>candidate.userId===member.userId);return <li key={member.userId}><Avatar displayName={member.username} size="sm"/><span><strong>{member.username}</strong><small>{member.seatNumber?`Seat ${member.seatNumber}`:'Spectator'} · {authorized?(player?.leaving?'LEAVING':player&&!player.connected?'DISCONNECTED':player?.participation.replace('_',' ')??member.state):'Session finished'}</small></span><b>{formatNumber(player?.tableChips??member.tableChips)}</b></li>})}</ul>}
  </aside>
}
