package com.ptit.poker.analytics.application.timebucket;

import com.ptit.poker.analytics.domain.timebucket.*;import java.sql.Date;import java.sql.ResultSet;import java.sql.SQLException;import java.sql.Timestamp;import java.time.*;import java.time.temporal.ChronoUnit;import java.util.*;
import org.springframework.context.annotation.Profile;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.*;import org.springframework.web.server.ResponseStatusException;import org.springframework.http.HttpStatus;

@Service @Profile("!bootstrap")
public class TimeBucketAnalyticsService {
    private final TimeBucketAnalyticsHistoryPort history;private final JdbcTemplate jdbc;private final Clock clock;private final ZoneId zone;private final BucketStatisticsCalculator calculator=new BucketStatisticsCalculator();
    public TimeBucketAnalyticsService(TimeBucketAnalyticsHistoryPort history,JdbcTemplate jdbc,Clock clock,AnalyticsProperties properties){this.history=history;this.jdbc=jdbc;this.clock=clock;this.zone=properties.getZoneId();}
    @Transactional(propagation=Propagation.REQUIRES_NEW) public void refreshCompletedSession(long sessionId){List<Target> targets=history.completedSessionHands(sessionId).stream().flatMap(h->java.util.stream.Stream.of(new Target(h.userId(),Kind.DAILY,AnalyticsBucket.day(h.finishedAt(),zone)),new Target(h.userId(),Kind.WEEKLY,AnalyticsBucket.week(h.finishedAt(),zone)))).distinct().sorted().toList();for(Target target:targets)refreshLocked(target);}
    @Transactional(propagation=Propagation.REQUIRES_NEW) public void refreshDaily(long userId,LocalDate date){refreshLocked(new Target(userId,Kind.DAILY,date));}
    @Transactional(propagation=Propagation.REQUIRES_NEW) public void refreshWeekly(long userId,LocalDate date){refreshLocked(new Target(userId,Kind.WEEKLY,AnalyticsBucket.monday(date)));}
    private void refreshLocked(Target target){String table=target.kind==Kind.DAILY?"daily_statistics":"weekly_statistics",key=target.kind==Kind.DAILY?"stat_date":"week_start_date";jdbc.update("INSERT IGNORE INTO "+table+"(user_id,"+key+",updated_at) VALUES(?,?,?)",target.userId,Date.valueOf(target.date),Timestamp.from(clock.instant()));jdbc.queryForObject("SELECT user_id FROM "+table+" WHERE user_id=? AND "+key+"=? FOR UPDATE",Long.class,target.userId,Date.valueOf(target.date));LocalDate endDate=target.kind==Kind.DAILY?target.date.plusDays(1):target.date.plusWeeks(1);Instant from=AnalyticsBucket.start(target.date,zone),to=AnalyticsBucket.start(endDate,zone);var hands=history.completedHands(target.userId,from,to);if(hands.isEmpty()){jdbc.update("DELETE FROM "+table+" WHERE user_id=? AND "+key+"=?",target.userId,Date.valueOf(target.date));return;}BucketStatistics value=calculator.calculate(hands,history.largestPotAward(target.userId,from,to));jdbc.update("UPDATE "+table+" SET hands_played=?,hands_won=?,hands_lost=?,hands_tied=?,chips_won=?,chips_lost=?,net_chips=?,largest_pot_won=?,playing_time_seconds=?,sessions_participated=?,updated_at=? WHERE user_id=? AND "+key+"=?",value.handsPlayed(),value.handsWon(),value.handsLost(),value.handsTied(),value.chipsWon(),value.chipsLost(),value.netChips(),value.largestPotWon(),value.playingTimeSeconds(),value.sessionsParticipated(),Timestamp.from(clock.instant()),target.userId,Date.valueOf(target.date));}
    @Transactional(readOnly=true) public List<Daily> daily(long userId,LocalDate from,LocalDate to){validateDaily(from,to);return jdbc.query("SELECT stat_date,hands_played,hands_won,hands_lost,hands_tied,chips_won,chips_lost,net_chips,largest_pot_won,playing_time_seconds,sessions_participated FROM daily_statistics WHERE user_id=? AND stat_date BETWEEN ? AND ? ORDER BY stat_date",(rs,n)->daily(rs),userId,Date.valueOf(from),Date.valueOf(to));}
    @Transactional(readOnly=true) public List<Weekly> weekly(long userId,LocalDate from,LocalDate to){validateOrder(from,to);LocalDate first=AnalyticsBucket.monday(from),last=AnalyticsBucket.monday(to);if(ChronoUnit.WEEKS.between(first,last)>103)bad();return jdbc.query("SELECT week_start_date,hands_played,hands_won,hands_lost,hands_tied,chips_won,chips_lost,net_chips,largest_pot_won,playing_time_seconds,sessions_participated FROM weekly_statistics WHERE user_id=? AND week_start_date BETWEEN ? AND ? ORDER BY week_start_date",(rs,n)->weekly(rs),userId,Date.valueOf(first),Date.valueOf(last));}
    @Transactional(readOnly=true) public Summary summary(long userId){LocalDate today=LocalDate.now(clock.withZone(zone)),week=AnalyticsBucket.monday(today);Daily daily=jdbc.query("SELECT stat_date,hands_played,hands_won,hands_lost,hands_tied,chips_won,chips_lost,net_chips,largest_pot_won,playing_time_seconds,sessions_participated FROM daily_statistics WHERE user_id=? AND stat_date=?",(rs,n)->daily(rs),userId,Date.valueOf(today)).stream().findFirst().orElse(Daily.zero(today));Weekly weekly=jdbc.query("SELECT week_start_date,hands_played,hands_won,hands_lost,hands_tied,chips_won,chips_lost,net_chips,largest_pot_won,playing_time_seconds,sessions_participated FROM weekly_statistics WHERE user_id=? AND week_start_date=?",(rs,n)->weekly(rs),userId,Date.valueOf(week)).stream().findFirst().orElse(Weekly.zero(week));return new Summary(daily,weekly);}
    private static Daily daily(ResultSet rs)throws SQLException{BucketStatistics s=stats(rs);return new Daily(rs.getObject(1,LocalDate.class),s.handsPlayed(),s.handsWon(),s.handsLost(),s.handsTied(),s.chipsWon(),s.chipsLost(),s.netChips(),s.largestPotWon(),s.playingTimeSeconds(),s.sessionsParticipated());}private static Weekly weekly(ResultSet rs)throws SQLException{LocalDate start=rs.getObject(1,LocalDate.class);BucketStatistics s=stats(rs);return new Weekly(start,start.plusDays(6),s.handsPlayed(),s.handsWon(),s.handsLost(),s.handsTied(),s.chipsWon(),s.chipsLost(),s.netChips(),s.largestPotWon(),s.playingTimeSeconds(),s.sessionsParticipated());}private static BucketStatistics stats(ResultSet rs)throws SQLException{return new BucketStatistics(rs.getLong(2),rs.getLong(3),rs.getLong(4),rs.getLong(5),rs.getLong(6),rs.getLong(7),rs.getLong(8),rs.getLong(9),rs.getLong(10),rs.getLong(11));}
    private static void validateDaily(LocalDate from,LocalDate to){validateOrder(from,to);if(ChronoUnit.DAYS.between(from,to)>365)bad();}private static void validateOrder(LocalDate from,LocalDate to){if(from.isAfter(to))bad();}private static void bad(){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"invalid analytics date range");}
    private enum Kind{DAILY,WEEKLY}private record Target(long userId,Kind kind,LocalDate date)implements Comparable<Target>{public int compareTo(Target other){int c=Long.compare(userId,other.userId);if(c==0)c=kind.compareTo(other.kind);return c==0?date.compareTo(other.date):c;}}
    public record Daily(LocalDate date,long handsPlayed,long handsWon,long handsLost,long handsTied,long chipsWon,long chipsLost,long netChips,long largestPotWon,long playingTimeSeconds,long sessionsParticipated){static Daily zero(LocalDate date){return new Daily(date,0,0,0,0,0,0,0,0,0,0);}}
    public record Weekly(LocalDate weekStartDate,LocalDate weekEndDate,long handsPlayed,long handsWon,long handsLost,long handsTied,long chipsWon,long chipsLost,long netChips,long largestPotWon,long playingTimeSeconds,long sessionsParticipated){static Weekly zero(LocalDate date){return new Weekly(date,date.plusDays(6),0,0,0,0,0,0,0,0,0,0);}}
    public record Summary(Daily today,Weekly currentWeek){}
}
