package com.ptit.poker.admin.infrastructure;

import com.ptit.poker.admin.application.*;import static com.ptit.poker.admin.application.AdminModels.*;import java.math.BigDecimal;import java.sql.*;import java.time.*;import java.util.*;import org.springframework.context.annotation.Profile;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Component;import org.springframework.web.server.ResponseStatusException;

@Component @Profile("!bootstrap")
public class JdbcAdminReadAdapter implements AdminReadPort {
 private final JdbcTemplate jdbc;public JdbcAdminReadAdapter(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public Overview overview(Instant generatedAt){return new Overview(count("users",null),count("users","account_status='ACTIVE'"),count("rooms",null),count("rooms","status IN ('WAITING','PLAYING')"),count("game_sessions","status='ACTIVE'"),count("game_sessions","status='FINISHED'"),count("poker_hands","ended_at IS NOT NULL"),Optional.ofNullable(jdbc.queryForObject("SELECT COALESCE(SUM(account_chips),0) FROM users",Long.class)).orElse(0L),generatedAt);}
 public Page<UserItem> users(int page,int size,String search,String status,String role){List<Object> args=new ArrayList<>();String where=userWhere(search,status,role,args);long total=scalar("SELECT COUNT(*) FROM users u LEFT JOIN player_profiles pp ON pp.user_id=u.id "+where,args);args.add(size);args.add(Math.multiplyExact(page,size));List<UserItem> items=jdbc.query("""
   SELECT u.id,u.username,u.email,u.role,u.account_status,u.account_chips,pp.display_name,u.created_at,
   COALESCE(pr.rating,1000),COALESCE(pr.games_rated,0),COALESCE(ps.total_games,0),COALESCE(ps.total_hands,0)
   FROM users u LEFT JOIN player_profiles pp ON pp.user_id=u.id LEFT JOIN player_rankings pr ON pr.user_id=u.id
   LEFT JOIN player_statistics ps ON ps.user_id=u.id
   """+where+" ORDER BY u.created_at DESC,u.id DESC LIMIT ? OFFSET ?",(rs,n)->new UserItem(rs.getLong(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getLong(6),rs.getString(7),instant(rs,8),rs.getInt(9),rs.getLong(10),rs.getLong(11),rs.getLong(12)),args.toArray());return new Page<>(items,page,size,total);}
 public UserDetail user(long id){List<UserDetail> rows=jdbc.query("""
   SELECT u.id,u.username,u.email,u.role,u.account_status,u.account_chips,pp.display_name,pp.avatar_url,pp.online_status,u.created_at,
   COALESCE(pr.rating,1000),COALESCE(pr.games_rated,0),COALESCE(pr.peak_rating,1000),COALESCE(ps.total_games,0),COALESCE(ps.total_hands,0),COALESCE(ps.total_wins,0),COALESCE(ps.total_losses,0),COALESCE(ps.win_rate,0),COALESCE(ps.total_chips_won,0),COALESCE(ps.total_chips_lost,0),COALESCE(ps.net_chip,0),COALESCE(ps.largest_pot_won,0),COALESCE(ps.average_playing_seconds,0)
   FROM users u LEFT JOIN player_profiles pp ON pp.user_id=u.id LEFT JOIN player_rankings pr ON pr.user_id=u.id LEFT JOIN player_statistics ps ON ps.user_id=u.id WHERE u.id=?
   """,(rs,n)->new UserDetail(rs.getLong(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getLong(6),rs.getString(7),rs.getString(8),rs.getString(9),instant(rs,10),rs.getInt(11),rs.getLong(12),rs.getInt(13),rs.getLong(14),rs.getLong(15),rs.getLong(16),rs.getLong(17),rs.getBigDecimal(18),rs.getLong(19),rs.getLong(20),rs.getLong(21),rs.getLong(22),rs.getLong(23),history(id)),id);return one(rows,"ADMIN_USER_NOT_FOUND","Admin user was not found");}
 public Page<RoomItem> rooms(int page,int size,String search,String status,String type){List<Object> args=new ArrayList<>();String where=roomWhere(search,status,type,args);long total=scalar("SELECT COUNT(*) FROM rooms r "+where,args);args.add(size);args.add(Math.multiplyExact(page,size));List<RoomItem> items=jdbc.query("""
   SELECT r.id,r.name,r.room_type,r.status,r.owner_user_id,
   SUM(CASE WHEN rp.left_at IS NULL AND rp.seat_number IS NOT NULL AND rp.player_state<>'SPECTATING' THEN 1 ELSE 0 END),
   SUM(CASE WHEN rp.left_at IS NULL AND rp.player_state='SPECTATING' THEN 1 ELSE 0 END),r.max_players,r.created_at,
   (SELECT gs.id FROM game_sessions gs WHERE gs.room_id=r.id AND gs.status='ACTIVE' ORDER BY gs.started_at DESC,gs.id DESC LIMIT 1)
   FROM rooms r LEFT JOIN room_players rp ON rp.room_id=r.id """+where+" GROUP BY r.id ORDER BY r.created_at DESC,r.id DESC LIMIT ? OFFSET ?",(rs,n)->new RoomItem(rs.getLong(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getLong(5),rs.getLong(6),rs.getLong(7),rs.getInt(8),instant(rs,9),nullableLong(rs,10)),args.toArray());return new Page<>(items,page,size,total);}
 public RoomDetail room(long id){List<RoomDetail> rows=jdbc.query("""
   SELECT r.id,r.name,r.room_type,r.status,r.owner_user_id,u.username,r.max_players,r.small_blind,r.big_blind,r.buy_in,r.created_at,
   (SELECT gs.id FROM game_sessions gs WHERE gs.room_id=r.id AND gs.status='ACTIVE' ORDER BY gs.started_at DESC,gs.id DESC LIMIT 1)
   FROM rooms r JOIN users u ON u.id=r.owner_user_id WHERE r.id=?
   """,(rs,n)->new RoomDetail(rs.getLong(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getLong(5),rs.getString(6),rs.getInt(7),rs.getLong(8),rs.getLong(9),rs.getLong(10),instant(rs,11),nullableLong(rs,12),participants(id)),id);return one(rows,"ADMIN_ROOM_NOT_FOUND","Admin room was not found");}
 public Page<GameItem> games(int page,int size,String status,Long roomId,Long userId,Instant from,Instant to){List<Object> args=new ArrayList<>();String where=gameWhere(status,roomId,userId,from,to,args);long total=scalar("SELECT COUNT(*) FROM game_sessions gs "+where,args);args.add(size);args.add(Math.multiplyExact(page,size));List<GameItem> items=jdbc.query("""
   SELECT gs.id,gs.room_id,gs.status,gs.started_at,gs.ended_at,
   (SELECT COUNT(DISTINCT hp.user_id) FROM poker_hands ph JOIN hand_players hp ON hp.poker_hand_id=ph.id WHERE ph.game_session_id=gs.id),
   (SELECT COUNT(*) FROM poker_hands ph WHERE ph.game_session_id=gs.id)
   FROM game_sessions gs """+where+" ORDER BY gs.started_at DESC,gs.id DESC LIMIT ? OFFSET ?",(rs,n)->new GameItem(rs.getLong(1),rs.getLong(2),rs.getString(3),instant(rs,4),nullableInstant(rs,5),rs.getLong(6),rs.getLong(7)),args.toArray());return new Page<>(items,page,size,total);}
 public GameDetail game(long id){List<GameDetail> rows=jdbc.query("SELECT gs.id,gs.room_id,r.name,gs.status,gs.started_at,gs.ended_at,(SELECT COUNT(*) FROM poker_hands ph WHERE ph.game_session_id=gs.id) FROM game_sessions gs JOIN rooms r ON r.id=gs.room_id WHERE gs.id=?",(rs,n)->new GameDetail(rs.getLong(1),rs.getLong(2),rs.getString(3),rs.getString(4),instant(rs,5),nullableInstant(rs,6),rs.getLong(7),gameParticipants(id)),id);return one(rows,"ADMIN_GAME_NOT_FOUND","Admin game session was not found");}
 public Page<HandItem> hands(long sessionId,int page,int size){if(sessionId<=0||Optional.ofNullable(jdbc.queryForObject("SELECT COUNT(*) FROM game_sessions WHERE id=?",Long.class,sessionId)).orElse(0L)==0)throw missing("ADMIN_GAME_NOT_FOUND","Admin game session was not found");long total=Optional.ofNullable(jdbc.queryForObject("SELECT COUNT(*) FROM poker_hands WHERE game_session_id=?",Long.class,sessionId)).orElse(0L);List<HandItem> items=jdbc.query("""
   SELECT ph.id,ph.hand_number,ph.started_at,ph.ended_at,(SELECT COUNT(*) FROM hand_players hp WHERE hp.poker_hand_id=ph.id),
   (SELECT COALESCE(SUM(pa.amount_awarded),0) FROM pots p JOIN pot_awards pa ON pa.pot_id=p.id WHERE p.poker_hand_id=ph.id),ph.final_phase,ph.end_reason,ph.board_cards
   FROM poker_hands ph WHERE ph.game_session_id=? ORDER BY ph.hand_number DESC LIMIT ? OFFSET ?
   """,(rs,n)->new HandItem(rs.getLong(1),rs.getLong(2),instant(rs,3),nullableInstant(rs,4),rs.getLong(5),rs.getLong(6),rs.getString(7),rs.getString(8),rs.getString(9)),sessionId,size,Math.multiplyExact(page,size));return new Page<>(items,page,size,total);}
 private List<RankingHistory> history(long id){return jdbc.query("SELECT game_session_id,old_rating,new_rating,rating_delta,session_net,placement,participant_count,created_at FROM ranking_history WHERE user_id=? ORDER BY created_at DESC,id DESC LIMIT 5",(rs,n)->new RankingHistory(rs.getLong(1),rs.getInt(2),rs.getInt(3),rs.getInt(4),rs.getLong(5),rs.getInt(6),rs.getInt(7),instant(rs,8)),id);}private List<RoomParticipant> participants(long id){return jdbc.query("SELECT rp.user_id,u.username,rp.seat_number,rp.player_state,rp.table_chips,rp.joined_at,rp.left_at FROM room_players rp JOIN users u ON u.id=rp.user_id WHERE rp.room_id=? ORDER BY rp.left_at IS NOT NULL,rp.seat_number,rp.user_id",(rs,n)->new RoomParticipant(rs.getLong(1),rs.getString(2),nullableInt(rs,3),rs.getString(4),rs.getLong(5),instant(rs,6),nullableInstant(rs,7)),id);}private List<GameParticipant> gameParticipants(long id){return jdbc.query("SELECT hp.user_id,u.username,SUM(hp.ending_table_chips-hp.starting_table_chips),COUNT(*) FROM poker_hands ph JOIN hand_players hp ON hp.poker_hand_id=ph.id JOIN users u ON u.id=hp.user_id WHERE ph.game_session_id=? GROUP BY hp.user_id,u.username ORDER BY hp.user_id",(rs,n)->new GameParticipant(rs.getLong(1),rs.getString(2),rs.getLong(3),rs.getLong(4)),id);}
 private String userWhere(String search,String status,String role,List<Object> args){List<String> p=new ArrayList<>();if(search!=null){p.add("(LOWER(u.username) LIKE LOWER(?) OR LOWER(COALESCE(u.email,'')) LIKE LOWER(?) OR LOWER(COALESCE(pp.display_name,'')) LIKE LOWER(?))");String q="%"+search+"%";args.add(q);args.add(q);args.add(q);}if(status!=null){p.add("u.account_status=?");args.add(status);}if(role!=null){p.add("u.role=?");args.add(role);}return where(p);}private String roomWhere(String search,String status,String type,List<Object> args){List<String> p=new ArrayList<>();if(search!=null){p.add("LOWER(r.name) LIKE LOWER(?)");args.add("%"+search+"%");}if(status!=null){p.add("r.status=?");args.add(status);}if(type!=null){p.add("r.room_type=?");args.add(type);}return where(p);}private String gameWhere(String status,Long roomId,Long userId,Instant from,Instant to,List<Object> args){List<String> p=new ArrayList<>();if(status!=null){p.add("gs.status=?");args.add(status);}if(roomId!=null){p.add("gs.room_id=?");args.add(roomId);}if(userId!=null){p.add("EXISTS(SELECT 1 FROM poker_hands ph JOIN hand_players hp ON hp.poker_hand_id=ph.id WHERE ph.game_session_id=gs.id AND hp.user_id=?)");args.add(userId);}if(from!=null){p.add("gs.started_at>=?");args.add(utc(from));}if(to!=null){p.add("gs.started_at<?");args.add(utc(to));}return where(p);}private static String where(List<String> predicates){return predicates.isEmpty()?"":" WHERE "+String.join(" AND ",predicates);}
 private long count(String table,String condition){return Optional.ofNullable(jdbc.queryForObject("SELECT COUNT(*) FROM "+table+(condition==null?"":" WHERE "+condition),Long.class)).orElse(0L);}private long scalar(String sql,List<Object> args){return Optional.ofNullable(jdbc.queryForObject(sql,Long.class,args.toArray())).orElse(0L);}private static <T>T one(List<T> rows,String code,String message){if(rows.isEmpty())throw missing(code,message);return rows.getFirst();}private static ResponseStatusException missing(String code,String message){return new ResponseStatusException(HttpStatus.NOT_FOUND,message+" ["+code+"]");}private static Instant instant(ResultSet rs,int column)throws SQLException{return rs.getObject(column,LocalDateTime.class).toInstant(ZoneOffset.UTC);}private static Instant nullableInstant(ResultSet rs,int column)throws SQLException{LocalDateTime value=rs.getObject(column,LocalDateTime.class);return value==null?null:value.toInstant(ZoneOffset.UTC);}private static LocalDateTime utc(Instant value){return LocalDateTime.ofInstant(value,ZoneOffset.UTC);}private static Long nullableLong(ResultSet rs,int column)throws SQLException{long value=rs.getLong(column);return rs.wasNull()?null:value;}private static Integer nullableInt(ResultSet rs,int column)throws SQLException{int value=rs.getInt(column);return rs.wasNull()?null:value;}
}
