CREATE TABLE rooms (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    owner_user_id BIGINT NOT NULL,
    room_type VARCHAR(20) NOT NULL,
    password_hash VARCHAR(255) NULL,
    max_players INT NOT NULL,
    small_blind BIGINT NOT NULL,
    big_blind BIGINT NOT NULL,
    buy_in BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'WAITING',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    last_activity_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT pk_rooms PRIMARY KEY (id),
    CONSTRAINT fk_rooms_owner_user FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT chk_rooms_room_type CHECK (room_type IN ('PUBLIC', 'PRIVATE')),
    CONSTRAINT chk_rooms_public_password CHECK (room_type = 'PRIVATE' OR password_hash IS NULL),
    CONSTRAINT chk_rooms_max_players CHECK (max_players BETWEEN 6 AND 9),
    CONSTRAINT chk_rooms_small_blind_positive CHECK (small_blind > 0),
    CONSTRAINT chk_rooms_big_blind_greater CHECK (big_blind > small_blind),
    CONSTRAINT chk_rooms_buy_in_positive CHECK (buy_in > 0),
    CONSTRAINT chk_rooms_status CHECK (status IN ('WAITING', 'PLAYING', 'FINISHED', 'CLOSED')),
    INDEX idx_rooms_owner_user_id (owner_user_id),
    INDEX idx_rooms_status_type (status, room_type),
    INDEX idx_rooms_last_activity_at (last_activity_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
