package com.ptit.poker.analytics.api;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import static org.assertj.core.api.Assertions.assertThat;import com.ptit.poker.auth.domain.*;import com.ptit.poker.auth.infrastructure.persistence.*;import com.ptit.poker.auth.infrastructure.security.JwtService;import com.ptit.poker.support.TestDatabaseSafetyInitializer;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.HttpHeaders;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.*;import org.springframework.test.web.servlet.MockMvc;

@EnabledIfEnvironmentVariable(named="TEST_DB_URL",matches=".+") @EnabledIfEnvironmentVariable(named="TEST_DB_USERNAME",matches=".+") @EnabledIfEnvironmentVariable(named="TEST_DB_PASSWORD",matches=".+")
@ActiveProfiles("test") @ContextConfiguration(initializers=TestDatabaseSafetyInitializer.class) @SpringBootTest @AutoConfigureMockMvc
class AnalyticsApiMySqlIntegrationTests {
 @Autowired MockMvc mvc;@Autowired UserRepository users;@Autowired JwtService jwt;@Autowired JdbcTemplate jdbc;private final List<Long> ids=new ArrayList<>();
 @AfterEach void cleanup(){for(long id:ids)jdbc.update("DELETE FROM users WHERE id=?",id);}
 @Test void allAnalyticsEndpointsRequireAuthentication()throws Exception{mvc.perform(get("/api/v1/analytics/me/daily?from=2026-08-01&to=2026-08-02")).andExpect(status().isUnauthorized());mvc.perform(get("/api/v1/analytics/me/weekly?from=2026-08-01&to=2026-08-02")).andExpect(status().isUnauthorized());mvc.perform(get("/api/v1/analytics/me/summary")).andExpect(status().isUnauthorized());}
 @Test void rangesAreChronologicalPrivateNormalizedAndValidated()throws Exception{UserEntity me=user(),other=user();insertDaily(me.getId(),LocalDate.of(2026,8,2),2);insertDaily(me.getId(),LocalDate.of(2026,8,4),4);insertDaily(other.getId(),LocalDate.of(2026,8,3),99);insertWeekly(me.getId(),LocalDate.of(2026,7,27),7);insertWeekly(me.getId(),LocalDate.of(2026,8,3),8);String token=bearer(me);mvc.perform(get("/api/v1/analytics/me/daily?from=2026-08-01&to=2026-08-05").header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(2)).andExpect(jsonPath("$[0].date").value("2026-08-02")).andExpect(jsonPath("$[0].handsPlayed").value(2)).andExpect(jsonPath("$[1].date").value("2026-08-04")).andExpect(jsonPath("$[1].handsPlayed").value(4));mvc.perform(get("/api/v1/analytics/me/weekly?from=2026-08-02&to=2026-08-09").header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(2)).andExpect(jsonPath("$[0].weekStartDate").value("2026-07-27")).andExpect(jsonPath("$[0].weekEndDate").value("2026-08-02")).andExpect(jsonPath("$[1].weekStartDate").value("2026-08-03")).andExpect(jsonPath("$[1].weekEndDate").value("2026-08-09"));for(String path:List.of("/daily?from=2026-08-02&to=2026-08-01","/daily?from=2025-01-01&to=2026-08-01","/weekly?from=2026-08-02&to=2026-08-01","/weekly?from=2024-01-01&to=2026-08-01","/daily?from=bad&to=2026-08-01"))mvc.perform(get("/api/v1/analytics/me"+path).header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isBadRequest());}
 @Test void summaryReturnsCurrentDataOrZerosWithoutCreatingRows()throws Exception{UserEntity with=user(),empty=user();LocalDate today=LocalDate.now(ZoneId.of("Asia/Bangkok")),week=today.with(java.time.temporal.TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY));insertDaily(with.getId(),today,3);insertWeekly(with.getId(),week,5);mvc.perform(get("/api/v1/analytics/me/summary").header(HttpHeaders.AUTHORIZATION,bearer(with))).andExpect(status().isOk()).andExpect(jsonPath("$.today.handsPlayed").value(3)).andExpect(jsonPath("$.currentWeek.handsPlayed").value(5));mvc.perform(get("/api/v1/analytics/me/summary").header(HttpHeaders.AUTHORIZATION,bearer(empty))).andExpect(status().isOk()).andExpect(jsonPath("$.today.handsPlayed").value(0)).andExpect(jsonPath("$.currentWeek.handsPlayed").value(0));assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM daily_statistics WHERE user_id=?",Long.class,empty.getId())).isZero();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM weekly_statistics WHERE user_id=?",Long.class,empty.getId())).isZero();}
 private UserEntity user(){String s=UUID.randomUUID().toString().replace("-","").substring(0,10);UserEntity u=users.saveAndFlush(new UserEntity("api8_"+s,"hash","api8_"+s+"@example.test",Role.PLAYER,AccountStatus.ACTIVE,5000));ids.add(u.getId());return u;}private String bearer(UserEntity user){return "Bearer "+jwt.createAccessToken(user);}private void insertDaily(long user,LocalDate date,long hands){jdbc.update("INSERT INTO daily_statistics(user_id,stat_date,hands_played,updated_at) VALUES(?,?,?,NOW(6))",user,date,hands);}private void insertWeekly(long user,LocalDate date,long hands){jdbc.update("INSERT INTO weekly_statistics(user_id,week_start_date,hands_played,updated_at) VALUES(?,?,?,NOW(6))",user,date,hands);}
}
