package com.ptit.poker.analytics.api;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.ptit.poker.auth.domain.*;import com.ptit.poker.auth.infrastructure.persistence.*;import com.ptit.poker.auth.infrastructure.security.JwtService;import com.ptit.poker.support.TestDatabaseSafetyInitializer;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.HttpHeaders;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.*;import org.springframework.test.web.servlet.MockMvc;
@EnabledIfEnvironmentVariable(named="TEST_DB_URL",matches=".+") @EnabledIfEnvironmentVariable(named="TEST_DB_USERNAME",matches=".+") @EnabledIfEnvironmentVariable(named="TEST_DB_PASSWORD",matches=".+") @ActiveProfiles("test") @ContextConfiguration(initializers=TestDatabaseSafetyInitializer.class) @SpringBootTest @AutoConfigureMockMvc
class RankingApiMySqlIntegrationTests {@Autowired MockMvc mvc;@Autowired UserRepository users;@Autowired JwtService jwt;@Autowired JdbcTemplate jdbc;private final List<Long> ids=new ArrayList<>();
 @AfterEach void cleanup(){for(long id:ids)jdbc.update("DELETE FROM users WHERE id=?",id);}
 @Test void allRankingEndpointsRequireAuthentication()throws Exception{mvc.perform(get("/api/v1/rankings/me")).andExpect(status().isUnauthorized());mvc.perform(get("/api/v1/rankings/leaderboard")).andExpect(status().isUnauthorized());mvc.perform(get("/api/v1/rankings/me/history")).andExpect(status().isUnauthorized());}
 @Test void meUsesJwtPrincipalAndUnratedReadCreatesNoRow()throws Exception{UserEntity authenticated=user(),other=user();jdbc.update("INSERT INTO player_rankings(user_id,rating,games_rated,peak_rating,updated_at) VALUES(?,1400,2,1450,NOW(6))",other.getId());mvc.perform(get("/api/v1/rankings/me").header(HttpHeaders.AUTHORIZATION,bearer(authenticated))).andExpect(status().isOk()).andExpect(jsonPath("$.userId").value(authenticated.getId())).andExpect(jsonPath("$.rating").value(1000)).andExpect(jsonPath("$.gamesRated").value(0)).andExpect(jsonPath("$.rank").doesNotExist());}
 @Test void authenticatedLeaderboardHistoryAndPaginationValidation()throws Exception{UserEntity user=user();String token=bearer(user);mvc.perform(get("/api/v1/rankings/leaderboard").header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isOk()).andExpect(jsonPath("$.page").value(0)).andExpect(jsonPath("$.size").value(20));mvc.perform(get("/api/v1/rankings/me/history").header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isOk()).andExpect(jsonPath("$").isArray());for(String endpoint:List.of("/api/v1/rankings/leaderboard","/api/v1/rankings/me/history")){for(String query:List.of("?page=-1","?size=0","?size=101"))mvc.perform(get(endpoint+query).header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isBadRequest());mvc.perform(get(endpoint+"?size=1").header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isOk());mvc.perform(get(endpoint+"?size=100").header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isOk());}}
 private UserEntity user(){String s=UUID.randomUUID().toString().replace("-","").substring(0,10);UserEntity u=users.saveAndFlush(new UserEntity("ra_"+s,"hash","ra_"+s+"@example.test",Role.PLAYER,AccountStatus.ACTIVE,5000));ids.add(u.getId());return u;}private String bearer(UserEntity user){return "Bearer "+jwt.createAccessToken(user);}}
