package com.ptit.poker.game.api.realtime;

public enum GameEventType {
    GAME_STARTED, HAND_STARTED, HOLE_CARDS, COMMUNITY_CARDS, YOUR_TURN,
    PLAYER_ACTION, GAME_STATE_UPDATE, SHOWDOWN, GAME_RESULT, HAND_FINISHED, COMMAND_ERROR
}
